runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:zbOeQdon+MA02A0mGFuQt3D+SRlb+U7J4Rq2Z4bN9s4=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  ## Google App engine only allows writing to tmp
  APP_SERVICES_CACHE: /tmp/services.php
  APP_PACKAGES_CACHE: /tmp/packages.php
  APP_CONFIG_CACHE: /tmp/config.php
  APP_ROUTES_CACHE: /tmp/routes.php

  SESSION_DRIVER: cookie
  
