runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:fygg5pSXb3OyU7RvYVxyvhIlj0Q1kdHLYOg1cpbfqEk=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie