version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  cloudrun: circleci/gcp-cloud-run@1.0.0
jobs:
  test:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            echo "TEST"
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build app binary and Docker image
          command: |
            echo "TEST2"
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV
            echo ${GCP_PROJECT_KEY} | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json

workflows:
  build_test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test